apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
spec:
  minReplicas: {{ .Values.hpa.nginxMinReplicas }}
  maxReplicas: {{ .Values.hpa.nginxMaxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  metrics:
  - type: Object
    object:
      target:
        kind: Service
        name: rest-metrics-service
      metricName: milli_requests
      targetValue: 10
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gunicorn-hpa
spec:
  minReplicas: {{ .Values.hpa.gunicornMinReplicas }}
  maxReplicas: {{ .Values.hpa.gunicornMaxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gunicorn-deployment
  targetCPUUtilizationPercentage: {{ .Values.hpa.gunicornCpuPercent }}
